.TH pione\-clean 1 "" "PIONE User Manual"
.SH NAME
.PP
pione\-clean \- remove PIONE\[aq]s temporary files, cache, and etc.
.SH SYNOPSIS
.PP
\f[B]pione\-clean\f[] [options]
.SH DESCRIPTION
.PP
pione\-clean removes PIONE\[aq]s temporary files, cache, and etc.
.SS NOTE
.PP
Package cache files are not removed if it is in package database.
.SH OPTIONS
.TP
.B \-\-older=\f[I]DATE\f[]
Remove files older than the date.
\f[I]DATE\f[] can be iso8601 format:
.RS
.IP
.nf
\f[C]
pione\-clean\ \-\-older=2013\-10\-01
\f[]
.fi
.PP
This means pione\-clean command removes files older than 2013\-10\-01.
Otherwise it can be days:
.IP
.nf
\f[C]
pione\-clean\ \-\-older=10
\f[]
.fi
.PP
This means pione\-clean command removes files older than 10 days.
.RE
.TP
.B \-\-type=\f[I]NAME\f[]
Remove only files of the type.
\f[I]NAME\f[] can be \f[I]temporary\f[], \f[I]file\-cache\f[],
\f[I]package\-cache\f[], or \f[I]profile\f[].
.RS
.RE
.SH EXAMPLES
.TP
.B pione\-clean
Remove all type files.
.RS
.RE
.TP
.B pione\-clean \-\-older=2013\-10\-01
Remove all type files older than 2013\-10\-01.
.RS
.RE
.TP
.B pione\-clean \-\-older=10
Remove all type files older than 10 days.
.RS
.RE
.TP
.B pione\-clean \-\-type=profile
Remove profile reports.
.RS
.RE
.TP
.B pione\-clean \-\-type=file\-cache \-\-older=30
Remove file cache files older than 30 days.
.RS
.RE
.SH REPORTING BUGS
.PP
Report bugs or feature requests to PIONE\[aq]s issue
tracker(https://github.com/pione/pione/issues).
.SH AUTHORS
Keita Yamaguchi.
