.TH pione\-action\-list 1 "" "PIONE User Manual"
.SH NAME
.PP
pione\-action\-list \- execute an action in literate action document.
.SH SYNOPSIS
.PP
\f[B]pione action:list\f[] [options] location
.SH DESCRIPTION
.PP
\f[B]action:list\f[] command lists action names in literate action
document.
.SH EXAMPLES
.TP
.B pione action:list HelloWorld.md
List all action names of \f[C]HelloWorld.md\f[].
.RS
.RE
.SH REPORTING BUGS
.PP
Report bugs or feature requests to PIONE\[aq]s issue
tracker(https://github.com/pione/pione/issues).
.SH AUTHORS
Keita Yamaguchi.
